# Simple workflow for deploying static content to GitHub Pages
name: Build docs based on Sphinx

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    environment:
      name: build-docs
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set working directory
        uses: ./.github/actions/set-working-directory
        with:
          working_directory: "${{ github.workspace }}"

      - name: Setup python environment
        uses: ./.github/actions/setup-python-env
        with:
          working_directory: "${{ env.WORKING_DIRECTORY }}"

      - name: Build docs
        run: |
          cd docs
          make html

      - uses: EndBug/add-and-commit@v9.1.1
        with:
          add: "${{ env.WORKING_DIRECTORY }}/docs/_build/html"
          default_author: github_actor
          fetch: true
          message: "[skip ci] Update docs"
          pathspec_error_handling: ignore
